# GRU-VAE 訓練配置檔案

# 資料設定
data:
  train_csv: '../data/train_small_processed.csv'
  train_split: 0.9  # 訓練集比例
  max_length: 100   # 最大序列長度

# 模型架構
model:
  model_type: 'gru'  # 'gru' 或 'transformer'
  # GRU 模型參數
  embedding_dim: 256
  hidden_dim: 512
  latent_dim: 128
  num_layers: 3
  dropout: 0.1
  bidirectional: true

  # model_type: 'transformer'
  # # Transformer 模型參數（當 model_type='transformer' 時使用）
  # d_model: 512
  # nhead: 8
  # num_encoder_layers: 8
  # num_decoder_layers: 6
  # dim_feedforward: 2048
  # max_len: 128

# 訓練參數
training:
  num_epochs: 150
  batch_size: 128
  learning_rate: 0.00075
  num_workers: 0

  # KL Annealing 設定
  kl_weight_start: 0.0
  kl_weight_end: 0.01
  kl_anneal_epochs: 100

  # 梯度裁剪
  grad_clip_max_norm: 1.0

# 驗證設定
validation:
  num_reconstruct: 10  # 顯示多少個重建範例
  num_sample: 10       # 顯示多少個採樣分子

# 檢查點設定
checkpoint:
  save_dir: './checkpoints_gru'
  save_interval: 5     # 每幾個 epoch 保存一次

# 設備設定
device:
  use_cuda: true       # 如果可用，使用 CUDA

# 隨機種子
seed: 42
